### PR TITLE
Bugfix for triggermatching

### PR DESCRIPTION
**Pull request by bartokm**
I discovered a bug (which I made) in commit https://github.com/cmkuo/ggAnalysis/commit/bbbd3656bd218c83ca2c843f8ad8d74d6129cca1
By simply changing the size of vectors, etc., I have overloaded the "UInt_t result" variable in triggermatching functions.
With this commit I propose a solution by making the variable ULong64_t.

### CODE REVIEW

**Comment by bartokm** [comment]
@cmkuo Can you please review and If you agree we can merge this PR.

**Comment by cmkuo** [comment]
@bartokm ok, this PR was merged. As soon as I know to fix a problem due to PR #9 , I will make a new tag.

**Comment by cmkuo** [comment]
@bartokm can you please help to fix this for 92X branch ?

**Comment by bartokm** [comment]
It's done! https://github.com/cmkuo/ggAnalysis/commit/f5cc5a2288d651febe4aff43343d2d711b09fc6b

**Pull request merged**
